[package]
name = "outro3"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
dashmap = "6.1.0"
crossbeam = "0.8"
pyo3 = { workspace = true }
scraper = "0.22"
ureq = "2"
url = "2"
